language: java

sudo: false

jdk:
  - oraclejdk8
os:
  - linux

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
  - "./build"

branches:
  only:
  - master

stages:
  - compile
  - code-quality
  - test
  - integrationTest
  - coverage

jobs:
  include:
  - stage: compile
    script:
    - "./gradlew compileKotlin"
    - "./gradlew compileTestKotlin"
    - "./gradlew compileIntegrationTestKotlin "

  - stage: code-quality
    script:
    - "./gradlew detektCheck"

  - stage: test
    script:
    - "./gradlew test"

  - stage: integrationTest
    script:
    - "./gradlew integrationTest"

  - stage: coverage
    script:
    - "./gradlew jacocoTestReport"
    - bash <(curl -s https://codecov.io/bash)
