spring:
  application:
    name: ratchet

logging:
  level:
    br.com.ratchet: DEBUG
  feign:
    type: FULL

feign:
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: application/json, text/csv
    response:
      enabled: true
  connectTimeout: 5000
  readTimeout: 5000
