spring:
  data:
    mongodb:
      uri: mongodb://${RATCHET_MONGO_USER}:${RATCHET_MONGO_PASSWORD}@nominus-prime-shard-00-00-hqvh9.mongodb.net:27017,nominus-prime-shard-00-01-hqvh9.mongodb.net:27017,nominus-prime-shard-00-02-hqvh9.mongodb.net:27017/test?ssl=true&replicaSet=nominus-prime-shard-0&authSource=admin

