spring:
  application:
    name: ratchet

camara:
  api: https://dadosabertos.camara.leg.br/api/v2/

cepesp:
  api: http://cepesp.io/api/consulta

witai:
  api: https://api.wit.ai
  token: ${WIT_AI_TOKEN}
  version: 20170307

logging:
  level:
    br.com.ratchet: DEBUG
  feign:
    type: FULL

feign:
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: application/json, text/csv
    response:
      enabled: true
  connectTimeout: 5000
  readTimeout: 5000
